version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "4200:4200"
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
      - /workspace/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
