version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/workspace
      - /workspace/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enables file watching in Docker
